### PR TITLE
WCCM22 - plot stability

### PR DESCRIPTION
**Pull request by LeilaGhaffari**
@jedbrown, I am creating this PR to discuss and ask my questions about the plots we want to show in WCCM 22.

I have used `Interpolations.jl` to interpolate $u = U   f_\eta$ and $T = T_\infty  h$ (assuming $U$ and $T_\infty$ are 1).
Now, The plots in `stability.ipynb` don't seem to be telling our story. I can plot the norm (like what we do in stable-numerics) but I wanted to check it with you first.

Also, I find that the transverse velocity, $v$, is defined by Kundu&Cohen as $$v = \frac{1}{2} \sqrt{ \frac{\nu U}{x} }  (\eta f^\prime - f)$$ I tried to compute it at the end of the notebook but my implementation is wrong. Could you give a look?

Thanks!

### CODE REVIEW

**Comment by jedbrown** [comment]
I see this code, which is effectively interpolating temperature (as one does when working in primitive variables).
```julia
T_lin, T_quad, T_spline = interps(h, x, η);   # T = T_∞ * h
```

I think you should also use LinearInterpolation to create a function $E(\eta) = \rho (e + u^2)$, then compute temperature as a function of $E$. So you've got two paths from the Blasius solution
* "primitive": $(f, h)$ continuously to Temperature, then linear interpolation to plot profile
* "conservative": $(f, h)$ continuously to conservative variables ($E$ in particular), linear interpolation of conservative variables, then plot temperature profil

**Comment by LeilaGhaffari** [comment]
Thanks! Does the new commit cover those two paths?

**Comment by jedbrown** [comment]
If you give me push access, I can push this version.
image

**Comment by jedbrown** [comment]
That's for Mach 1 and h_wall = h_infty = 1.

**Comment by LeilaGhaffari** [comment]
Beautiful! Just invited you! Thanks!

**Comment by jedbrown** [comment]
Done. For p=2, I think the approach using Interpolations.jl is kind of wrong. It's using solution values at the same nodes, then creating a spline through those points (which means the interpolant depends on data from far away and the boundary conditions).
image

This is different from having a nodally exact solution in a high order finite element space, which is more like what happens in a finite element solver and I think would be informative to show. I don't know if there's a convenient library so it might be appropriate to code up by hand. To do that, you need to make an evaluation function that locates the input point $x$ within the implied finite elements. You used `n = 10` points in this notebook, but if you make it `n = 11`, then you'd have 5 elements. For quadratic, the evaluation nodes are still the midpoints so you can use the same sampled nodes. I wouldn't bother with cubic.

**Comment by LeilaGhaffari** [comment]
Thanks for the fix! Oops, messed up the mapping!
Okay, I'll work on the p=2 case. After all, our story wouldn't be complete if we didn't compared p=1 with higher orders (p=2).
I know we don't care about p=3 right now, but does `CubicSplineInterpolation()` look correct? Or the same problem exists with p=3?

**Comment by jedbrown** [comment]
Cubic splines have basically the same problem as quadratics. They're losing fidelity at the boundary because their boundary condition doesn't enforce the physics (and thus is dependent on the coarse sampling of points from rather far away). It'll converge under refinement, but we really want nodally exact Lagrange elements here to explain the problem.

**Comment by LeilaGhaffari** [comment]
OK, this last commit is definitely not correct. I stole most parts from your notebook but got lost in the modification. I guess what I am not sure about is what is going to be saved in the interpolation process to be used in the extrapolation (like how we compute the polynomial coefficients in the classical interpolation.
Also, the interpolation itself is not correct. It seems I am not using your element restriction matrix correctly since the values on the shared nodes are somehow doubled.

**Comment by jedbrown** [comment]
Pushed updates. I'll share figures for discussion in Zulip.

**Pull request merged**
